#
# Copyright (c) 2019 Connexta, LLC
#
# Released under the GNU Lesser General Public License version 3; see
# https://www.gnu.org/licenses/lgpl-3.0.html
#

openapi: 3.0.2

info:
  version: ${project.version}
  title: Query API
  description: >
    The Query API is defined to provide clients with the ability to
    query for stored products.
  contact:
    name: Connexta
  license:
    name: GNU Lesser General Public License
    url: 'http://www.gnu.org/licenses/lgpl.html'

servers:
  - url: ${rest.server.url}

paths:
  /search:
    get:
      summary: Query endpoint for products.
      description: >
        A system can use the Query endpoint to perform a keyword search on stored products.
      operationId: query
      tags:
        - query
      parameters:
        - $ref: '#/components/parameters/Accept-Version'
        - $ref: '#/components/parameters/Keyword'
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '501':
          $ref: '#/components/responses/NotImplemented'
        'default':
          $ref: '#/components/responses/DefaultError'

components:
  responses:
    Ok:
      description: >
        The query request was successful and a list of retrieve URIs is returned in descending order from
        most matched to least matched.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/QueryResults'
    Unauthorized:
      description: >
        The client could not be authenticated.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    Forbidden:
      description: >
        The client does not have permission.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    NotImplemented:
      description: >
        The requested API version is not supported and therefore not implemented.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    BadRequest:
      description: >
        The client message could not understood by the server due to invalid format or syntax.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    DefaultError:
      description: >
        Any other possible errors not currently known.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'

  parameters:
    Accept-Version:
      name: Accept-Version
      in: header
      description: >
        The minimal API version that a client using this API will accept
        responses from.
      required: true
      schema:
        $ref: '#/components/schemas/Version'
    Keyword:
      name: q
      in: query
      schema:
        type: string
        minLength: 1
        example: "house"
      description: >
        The keyword that will be used in the query.
      required: true

  headers:
    ContentVersion:
      description: >
        The API version used by the server to produce the REST message. The server will accept
        messages for any minor versions prior to this one.
      required: true
      schema:
        $ref: '#/components/schemas/Version'
      examples:
        major.minor:
          value: '1.2'
          summary: A released minor version
        major.minor.patch:
          value: '1.0.3'
          summary: A patched version
        dev:
          value: '1.2.0-SNAPSHOT'
          summary: A development version

  schemas:
    Version:
      description: Version number.
      type: string
      minLength: 3
      maxLength: 80
      pattern: '^([1-9]([0-9]+)?)\.(0|([1-9]([0-9]+)?))(\.(0|([1-9]([0-9]+)?))(-.*)?)?$'
      example: 1.2, 2.4.3, 0.2.5-SNAPSHOT
    QueryResults:
      description: >
        A list of retrieve URIs that represent all of the products that matched the query.
      type: object
      properties:
        productIds:
          type: array
          items:
            type: string
            format: uri
    ErrorMessage:
      description: Error message information.
      type: object
      required:
        - timestamp
        - path
        - status
        - error
        - message
      properties:
        timestamp:
          type: string
          format: date-time
          description: The server time when the error was generated.
          example: 2019-05-09T14:47:13.101+0000
        path:
          type: string
          description: The path for the REST request that generated this error.
          example: /search
        status:
          type: integer
          format: int32
          description: The corresponding HTTP status code.
          example: 200
        code:
          type: integer
          format: int32
          description: >
            An optional more specific code corresponding to the error (specific codes need to be
            documented).
        error:
          type: string
          description: The corresponding HTTP reason phrase.
          minLength: 1
          example: Bad Request
        message:
          type: string
          description: Specific information about the error.
          minLength: 1
          example: Validation failed for object='systemInfo'.
        details:
          type: array
          items:
            type: string
          description: Optional detailed information about the error.